fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.15.0'
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.11.0'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '2.2.0'
  symlinks:
    puppet: "#{source_dir}"
